### ISSUE TITLE
UserActonFragment.java:39: 错误: Unable to parse @Bind binding.

### ISSUE THREAD

**Issue by y-young** [ZhangZhenghao/MaterialWeCenter#16]
Gradle编译时出现以下错误：
app\src\main\java\com\sine_x\material_wecenter\controller\fragment\UserActonFragment.java:39: 错误: Unable to parse @Bind binding.
    RecyclerView mRecyclerView;
app\src\main\java\com\sine_x\material_wecenter\controller\adapter\ActionViewAdapter.java:82: 错误: Unable to parse @Bind binding.
        @Bind(R.id.card_view) CardView card;
（类似的错误还有好几个）
48 个错误
:app:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

希望能够给出一些指导或尽快修复，谢谢

**Comment by zhenghaoz** [comment]
感谢反馈。

看起来应该是ButterKnife这个库依赖没有处理好，我自己编译是没有问题的。不太容易看出什么地方出了偏差，build.gradle配置sync好了没？网络访问maven仓库是否畅通？或者告诉我更加详细的信息？

**Comment by y-young** [comment]
@ZhangZhenghao 感谢回复。已经改用Android Studio编译成功，但是无法进行发表回复、帖子点赞等操作，点击提交后程序崩溃
D/Error: ERR: class=com.qmemorize.forum.Client
01-27 20:16:14.710 1488-1612/? D/Error: ERR: stack=java.lang.RuntimeException: An error occured while executing doInBackground()
                                            at android.os.AsyncTask$3.done(AsyncTask.java:304)
                                            at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
                                            at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
                                            at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                            at java.lang.Thread.run(Thread.java:818)
                                         Caused by: java.lang.StackOverflowError: stack size 1036KB
                                            at com.qmemorize.forum.Client.doPost(Client.java:334)
此问题已在Pull Request #17 中修复

**Comment by y-young** [comment]
@ZhangZhenghao 还有一个问题就是目前的签名和API地址都有误，在Config.java中好多API地址前误加了HOST_NAME或是后面误加了“/”导致404，希望能够尽快修复，顺便祝春节快乐，谢谢！

**Comment by zhenghaoz** [comment]
感谢帮我解决了之前重构(T_T)时引入的bug。

**Comment by y-young** [comment]
@ZhangZhenghao 还有一个API地址错误导致无法获取数据的问题希望能尽快修复。谢谢

**Comment by zhenghaoz** [comment]
@Y-Young API的URL问题已经修复，现在还有很多小问题，我暂时还没有时间完成

**Comment by y-young** [comment]
@ZhangZhenghao 非常感谢，期待更多新功能的加入
